# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{phocoder-rb}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy Green"]
  s.date = %q{2011-07-13}
  s.description = %q{The ruby client for the phocoder.com API.}
  s.email = %q{jagthedrummer@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/phocoder.rb",
    "lib/phocoder/base.rb",
    "lib/phocoder/errors.rb",
    "lib/phocoder/extensions.rb",
    "lib/phocoder/http.rb",
    "lib/phocoder/http/net_http.rb",
    "lib/phocoder/http/typhoeus.rb",
    "lib/phocoder/job.rb",
    "lib/phocoder/phocoder.rb",
    "lib/phocoder/response.rb",
    "phocoder-rb.gemspec",
    "spec/phocoder/http/net_http_spec.rb",
    "spec/phocoder/http/typhoeus_spec.rb",
    "spec/phocoder/http_spec.rb",
    "spec/phocoder/job_spec.rb",
    "spec/phocoder/phocoder_spec.rb",
    "spec/phocoder/response_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jagthedrummer/phocoder-rb}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{The ruby client for the phocoder.com API.}
  s.test_files = [
    "spec/phocoder/http/net_http_spec.rb",
    "spec/phocoder/http/typhoeus_spec.rb",
    "spec/phocoder/http_spec.rb",
    "spec/phocoder/job_spec.rb",
    "spec/phocoder/phocoder_spec.rb",
    "spec/phocoder/response_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<webmock>, ["~> 1.6.0"])
    else
      s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<webmock>, ["~> 1.6.0"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.1.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<webmock>, ["~> 1.6.0"])
  end
end

